### ISSUE TITLE
No response from request_vote

### ISSUE THREAD

**Issue by maksimdrachov** [OpenCyphal-Garage/cyraft#1]
I'm trying to get a response from `request_vote`, after sending a request using Yakut.

The issue is that I'm not getting any response, and the request times out:

![issue-1-no-response](https://user-images.githubusercontent.com/39975120/232752742-c5962c0b-facf-4514-89e0-26c4839e6ee6.png)

The demo node does appear to receive the request correctly:

![issue-1-request-received](https://user-images.githubusercontent.com/39975120/232752799-b42534db-70e1-4c60-9809-350897e0dcbc.png)

(When running in debug mode, putting a breakpoint on the entrance of `_serve_request_vote`, it appears to hang on the return statement)

The code implementing this `request_vote` functionality is as follows:

- Add `srv_request_vote` to be served in the background:

    ```py
    # Create an RPC-server. (RequestVote)
    try:
        _logger.info("Request vote service is enabled")
        srv_request_vote = self._node.get_server(
            sirius_cyber_corp.RequestVote_1, "request_vote"
        )
        srv_request_vote.serve_in_background(self._serve_request_vote)
    except pycyphal.application.register.MissingRegisterError:
        _logger.info(
            "The request vote service is disabled by configuration (UAVCAN__SRV__REQUEST_VOTE__ID missing)"
        )
    ```

- The `_serve_request_vote` function itself:

    ```py
    @staticmethod
    async def _serve_request_vote(
        # self,
        request: sirius_cyber_corp.RequestVote_1.Request,
        metadata: pycyphal.presentation.ServiceRequestMetadata,
    ) -> sirius_cyber_corp.RequestVote_1.Response:
        _logger.info(
            "\033[94m Request vote request %s from node %d \033[0m",
            request,
            metadata.client_node_id,
        )

        return sirius_cyber_corp.RequestVote_1.Response(
            term=1,
            vote_granted=True,
        )
    ```

This is pretty much the same way it is done in the demo example from pycyphal.

The only thing I'm unclear about is whether it might have something to do the way `run()` is implemented:

```py
async def run(self) -> None:
    """
    The main method that runs the business logic. It is also possible to use the library in an IoC-style
    by using receive_in_background() for all subscriptions if desired.
    """
    _logger.info("Application Node started!")
    _logger.info("Running. Press Ctrl+C to stop.")

    while True:
        await asyncio.sleep(0.1)
```

In the demo example, there's more setup code here, however nothing related to the service (`least_square` in their case.)

I suspect maybe I need to use the library in "IoC-style by using receive_in_background()", however not sure how this looks in code, please bear with me and use simple words.

**Comment by pavel-kirienko** [comment]
The code looks correct to me, at least I don't see any obvious issues. Which transport are you using and what is the node-ID of Yakut? You should inspect verbose logs from both Yakut and your application. There will be a lot of output but in that output there will be useful information regarding the lost transfer. At least you'll know if the response is actually being sent.

**Comment by maksimdrachov** [comment]
Ok, it was this:

```py
@staticmethod
async def _serve_request_vote(
    # self,
    request: sirius_cyber_corp.RequestVote_1.Request,
    metadata: pycyphal.presentation.ServiceRequestMetadata,
) -> sirius_cyber_corp.RequestVote_1.Response:
    _logger.info(
        "\033[94m Request vote request %s from node %d \033[0m",
        request,
        metadata.client_node_id,
    )

    return sirius_cyber_corp.RequestVote_1.Response(
        term=1,
        voteGranted=True, # <---- previously wrong argument name here
    )
```

Shows up in the log as follows:

![image](https://user-images.githubusercontent.com/39975120/232761171-56429a02-eabf-4812-9806-d78863538ec7.png)
